title: Matějův blog
logo: /assets/img/logo.png
show_downloads: false
color-scheme: dark

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Home
    icon: <i class="fa-solid fa-house-chimney"></i>
    link: https://matejhosek.github.io/
    
  - name: About
    icon: <i class="fa-solid fa-circle-info"></i>
    link: https://matejhosek.github.io/about

    icon: <i class="fa-solid fa-pencil"></i>
    link: https://matejhosek.github.io/notes

  - name: Articles
    icon: <i class="fa-solid fa-newspaper"></i>
    link: https://matejhosek.github.io/articles

  - name: References
    icon: <i class="fa-solid fa-paper-plane"></i>
    link: https://matejhosek.github.io/references
  - name: Notes

  - name: Repository
    icon: <i class="fa-sharp fa-solid fa-code"></i>
    link: https://github.com/MatejHosek/MatejHosek.github.io

plugins:
  - jektex
